import Head from "next/head";
import Image from "next/image";
import styles from "./index.module.scss";

export default function Home() {
  return (
    <div className="border-blue-400 border min-h-screen flex flex-col items-center">
      <Head>
        <title>FIFA World Cup Standings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="w-full max-w-7xl border-green-600 border">
        <h1 className={styles.pageTitle}>
          FIFA World Cup Qatar 2022 Standings
        </h1>
        <section>
          <h4 className="">Format</h4>
          <p>
            The International 2022 is the concluding tournament of the Dota Pro
            Circuit and the eleventh annual edition of The International which
            returns to Asia for the second time. The invite format is similar to
            the one used for the preceding International, whereby a point system
            based on official sponsored Regional Leagues and Majors will be used
            to determine the teams invited to The International. It was
            announced that the second and third place teams from each region's
            qualifiers will compete in a Last Chance Qualifier prior to The
            International to determine two additional qualification spots - thus
            expanding the amount of teams in the group stage for this year's
            International from 18 to 20 teams.[1] This year's International will
            be the first occasion where the main event is played out on two
            different venues: the Playoffs at SunTec Singapore followed by the
            Finals at Singapore Indoor Stadium.[2]{" "}
          </p>
          <p>
            The International 2022 is the concluding tournament of the Dota Pro
            Circuit and the eleventh annual edition of The International which
            returns to Asia for the second time. The invite format is similar to
            the one used for the preceding International, whereby a point system
            based on official sponsored Regional Leagues and Majors will be used
            to determine the teams invited to The International. It was
            announced that the second and third place teams from each region's
            qualifiers will compete in a Last Chance Qualifier prior to The
            International to determine two additional qualification spots - thus
            expanding the amount of teams in the group stage for this year's
            International from 18 to 20 teams.[1] This year's International will
            be the first occasion where the main event is played out on two
            different venues: the Playoffs at SunTec Singapore followed by the
            Finals at Singapore Indoor Stadium.[2]{" "}
          </p>
          <p>
            The International 2022 is the concluding tournament of the Dota Pro
            Circuit and the eleventh annual edition of The International which
            returns to Asia for the second time. The invite format is similar to
            the one used for the preceding International, whereby a point system
            based on official sponsored Regional Leagues and Majors will be used
            to determine the teams invited to The International. It was
            announced that the second and third place teams from each region's
            qualifiers will compete in a Last Chance Qualifier prior to The
            International to determine two additional qualification spots - thus
            expanding the amount of teams in the group stage for this year's
            International from 18 to 20 teams.[1] This year's International will
            be the first occasion where the main event is played out on two
            different venues: the Playoffs at SunTec Singapore followed by the
            Finals at Singapore Indoor Stadium.[2]{" "}
          </p>
          <p>
            The International 2022 is the concluding tournament of the Dota Pro
            Circuit and the eleventh annual edition of The International which
            returns to Asia for the second time. The invite format is similar to
            the one used for the preceding International, whereby a point system
            based on official sponsored Regional Leagues and Majors will be used
            to determine the teams invited to The International. It was
            announced that the second and third place teams from each region's
            qualifiers will compete in a Last Chance Qualifier prior to The
            International to determine two additional qualification spots - thus
            expanding the amount of teams in the group stage for this year's
            International from 18 to 20 teams.[1] This year's International will
            be the first occasion where the main event is played out on two
            different venues: the Playoffs at SunTec Singapore followed by the
            Finals at Singapore Indoor Stadium.[2]{" "}
          </p>
          <p>
            The International 2022 is the concluding tournament of the Dota Pro
            Circuit and the eleventh annual edition of The International which
            returns to Asia for the second time. The invite format is similar to
            the one used for the preceding International, whereby a point system
            based on official sponsored Regional Leagues and Majors will be used
            to determine the teams invited to The International. It was
            announced that the second and third place teams from each region's
            qualifiers will compete in a Last Chance Qualifier prior to The
            International to determine two additional qualification spots - thus
            expanding the amount of teams in the group stage for this year's
            International from 18 to 20 teams.[1] This year's International will
            be the first occasion where the main event is played out on two
            different venues: the Playoffs at SunTec Singapore followed by the
            Finals at Singapore Indoor Stadium.[2]{" "}
          </p>
          <p>
            The International 2022 is the concluding tournament of the Dota Pro
            Circuit and the eleventh annual edition of The International which
            returns to Asia for the second time. The invite format is similar to
            the one used for the preceding International, whereby a point system
            based on official sponsored Regional Leagues and Majors will be used
            to determine the teams invited to The International. It was
            announced that the second and third place teams from each region's
            qualifiers will compete in a Last Chance Qualifier prior to The
            International to determine two additional qualification spots - thus
            expanding the amount of teams in the group stage for this year's
            International from 18 to 20 teams.[1] This year's International will
            be the first occasion where the main event is played out on two
            different venues: the Playoffs at SunTec Singapore followed by the
            Finals at Singapore Indoor Stadium.[2]{" "}
          </p>
          <p>
            The International 2022 is the concluding tournament of the Dota Pro
            Circuit and the eleventh annual edition of The International which
            returns to Asia for the second time. The invite format is similar to
            the one used for the preceding International, whereby a point system
            based on official sponsored Regional Leagues and Majors will be used
            to determine the teams invited to The International. It was
            announced that the second and third place teams from each region's
            qualifiers will compete in a Last Chance Qualifier prior to The
            International to determine two additional qualification spots - thus
            expanding the amount of teams in the group stage for this year's
            International from 18 to 20 teams.[1] This year's International will
            be the first occasion where the main event is played out on two
            different venues: the Playoffs at SunTec Singapore followed by the
            Finals at Singapore Indoor Stadium.[2]{" "}
          </p>
          <p>
            The International 2022 is the concluding tournament of the Dota Pro
            Circuit and the eleventh annual edition of The International which
            returns to Asia for the second time. The invite format is similar to
            the one used for the preceding International, whereby a point system
            based on official sponsored Regional Leagues and Majors will be used
            to determine the teams invited to The International. It was
            announced that the second and third place teams from each region's
            qualifiers will compete in a Last Chance Qualifier prior to The
            International to determine two additional qualification spots - thus
            expanding the amount of teams in the group stage for this year's
            International from 18 to 20 teams.[1] This year's International will
            be the first occasion where the main event is played out on two
            different venues: the Playoffs at SunTec Singapore followed by the
            Finals at Singapore Indoor Stadium.[2]{" "}
          </p>
          <p>
            The International 2022 is the concluding tournament of the Dota Pro
            Circuit and the eleventh annual edition of The International which
            returns to Asia for the second time. The invite format is similar to
            the one used for the preceding International, whereby a point system
            based on official sponsored Regional Leagues and Majors will be used
            to determine the teams invited to The International. It was
            announced that the second and third place teams from each region's
            qualifiers will compete in a Last Chance Qualifier prior to The
            International to determine two additional qualification spots - thus
            expanding the amount of teams in the group stage for this year's
            International from 18 to 20 teams.[1] This year's International will
            be the first occasion where the main event is played out on two
            different venues: the Playoffs at SunTec Singapore followed by the
            Finals at Singapore Indoor Stadium.[2]{" "}
          </p>
          <p>
            The International 2022 is the concluding tournament of the Dota Pro
            Circuit and the eleventh annual edition of The International which
            returns to Asia for the second time. The invite format is similar to
            the one used for the preceding International, whereby a point system
            based on official sponsored Regional Leagues and Majors will be used
            to determine the teams invited to The International. It was
            announced that the second and third place teams from each region's
            qualifiers will compete in a Last Chance Qualifier prior to The
            International to determine two additional qualification spots - thus
            expanding the amount of teams in the group stage for this year's
            International from 18 to 20 teams.[1] This year's International will
            be the first occasion where the main event is played out on two
            different venues: the Playoffs at SunTec Singapore followed by the
            Finals at Singapore Indoor Stadium.[2]{" "}
          </p>
          <p>
            The International 2022 is the concluding tournament of the Dota Pro
            Circuit and the eleventh annual edition of The International which
            returns to Asia for the second time. The invite format is similar to
            the one used for the preceding International, whereby a point system
            based on official sponsored Regional Leagues and Majors will be used
            to determine the teams invited to The International. It was
            announced that the second and third place teams from each region's
            qualifiers will compete in a Last Chance Qualifier prior to The
            International to determine two additional qualification spots - thus
            expanding the amount of teams in the group stage for this year's
            International from 18 to 20 teams.[1] This year's International will
            be the first occasion where the main event is played out on two
            different venues: the Playoffs at SunTec Singapore followed by the
            Finals at Singapore Indoor Stadium.[2]{" "}
          </p>
        </section>
      </main>
    </div>
  );
}

function Header() {
  return (
    <header className="w-full max-w-7xl border-green-600 border mb-4 mt-4">
      <img src="fifastandings.svg" className={styles.logo} />
    </header>
  );
}
